# Generated by Django 4.2.5 on 2023-12-29 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_growth_loop', '0002_rename_descricao_repositorioideias_descricao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RepositorioIdeias',
            new_name='Repositorio_Ideias',
        ),
    ]
