# Generated by Django 4.2.5 on 2023-12-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_growth_loop', '0004_repositorio_ideias_metrica'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorio_ideias',
            name='gatilho',
            field=models.CharField(choices=[('CTR', 'CTR'), ('TAXA DE CONVERSÃO LEADS X VISITAS', 'Taxa de Conversão Leads x Visitas'), ('TAXA DE CONVERSÃO OPORTUNIDADES X LEADS', 'Taxa de conversão Oportunidades x Leads'), ('TAXA DE CONVERSÃO VENDAS X OPORTUNIDADES', 'Taxa de COnversão Vendas x Oportunidades'), ('CHURN RATE', 'Churn Rate'), ('TAXA DE ENGAJAMENTO', 'Taxa de Engajamento'), ('CAC', 'CAC')], default='', max_length=100),
        ),
    ]
