# Generated by Django 4.2.5 on 2023-12-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_growth_loop', '0005_repositorio_ideias_gatilho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorio_ideias',
            name='gatilho',
            field=models.CharField(choices=[('ACIMA DA MÉDIA', 'Acima da Média'), ('ABAIXO DA MÉDIA', 'Abaixo da Média')], default='', max_length=100),
        ),
    ]
