# Generated by Django 4.2.5 on 2023-12-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_growth_loop', '0006_alter_repositorio_ideias_gatilho'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorio_ideias',
            name='etapa',
            field=models.CharField(choices=[('AWARENESS', 'Awareness'), ('AQUISIÇÃO', 'Aquisição'), ('ATIVAÇÃO', 'Ativação'), ('RETENÇÃO', 'Retenção'), ('RECEITA', 'Receita'), ('RECOMENDAÇÃO', 'Recomendação')], default='', max_length=100),
        ),
    ]
