# Generated by Django 4.2.5 on 2023-12-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_growth_loop', '0007_repositorio_ideias_etapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorio_ideias',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
