# Generated by Django 4.2.5 on 2023-12-30 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_growth_loop', '0008_repositorio_ideias_publicada'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repositorio_Ideias',
            new_name='Ideias',
        ),
    ]
