# Generated by Django 4.2.5 on 2023-12-30 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_growth_loop', '0009_rename_repositorio_ideias_ideias'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideias',
            name='data_ideia',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
