# Generated by Django 4.2.5 on 2023-12-30 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_growth_loop', '0010_ideias_data_ideia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metricas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_metrica', models.CharField(max_length=100)),
                ('valor_metrica', models.FloatField()),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
