# Generated by Django 4.2.5 on 2024-01-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_growth_loop', '0015_alter_metricas_valor_metrica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricas',
            name='valor_metrica',
            field=models.FloatField(),
        ),
    ]
